---
services: docker

env:
  - path: nginx/minimal
    url: http://localhost

  - path: nginx/proxy-to-virtual-path
    url: http://localhost/documentserver-virtual-path
    
  - path: nginx/proxy-https-to-http
    ssl: true
    config: ../../../nginx/proxy-https-to-http.conf 
    url: https://localhost

  - path: apache/minimal
    url: http://localhost

  - path: apache/proxy-to-virtual-path
    url: http://localhost/documentserver-virtual-path

  - path: apache/proxy-https-to-http    
    ssl: true 
    config: ../../../apache/proxy-https-to-http.conf
    url: https://localhost

  - path: apache/proxy-https-to-https    
    ssl: true
    ssl_backend: true
    config: ../../../apache/proxy-https-to-https.conf
    url: https://localhost
    
  - path: haproxy/minimal
    url: http://localhost

  - path: haproxy/active-active
    url: http://localhost

  - path: haproxy/hot-standby
    config: ../../../haproxy/hot-standby.cfg
    url: http://localhost

  - path: haproxy/proxy-to-virtual-path
    url: http://localhost/documentserver-virtual-path

  - path: haproxy/proxy-https-to-http    
    ssl: true 
    config: ../../../haproxy/proxy-https-to-http.cfg
    url: https://localhost

  - path: traefik/minimal
    url: http://localhost

  - path: traefik/proxy-https-to-http
    ssl: true 
    config: ../../../traefik/proxy-https-to-http.toml
    url: https://localhost

script:
  # Go to tests dir
  - cd ${PWD}/tests

  # Run test.
  - ./test.sh
